# Generated by Django 5.2.7 on 2025-10-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_participante_vendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='apellidos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='participante',
            name='nombres',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='participante',
            name='vendedor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
