# Generated by Django 5.2.7 on 2025-10-16 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_alter_participante_apellidos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Previaparticipantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_part', models.CharField(max_length=100, unique=True)),
                ('nombres', models.CharField(blank=True, max_length=255, null=True)),
                ('dni', models.CharField(blank=True, max_length=20, null=True)),
                ('asesor', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='vouchers/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('validado_contabilidad', models.BooleanField(default=False)),
                ('validado_administracion', models.BooleanField(default=False)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='cliente.previaparticipantes')),
            ],
        ),
    ]
