# Generated by Django 5.2.7 on 2025-10-16 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_previaparticipantes_qr_image_delete_voucher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='vouchers/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('validado_contabilidad', models.BooleanField(default=False)),
                ('validado_administracion', models.BooleanField(default=False)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='cliente.previaparticipantes')),
            ],
        ),
    ]
