# Generated by Django 5.2.7 on 2025-10-17 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0008_voucher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previaparticipantes',
            name='cod_part',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
