# Generated by Django 5.2.6 on 2025-09-09 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_cliente', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=20, unique=True)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('celular', models.CharField(max_length=20, unique=True)),
                ('correo', models.CharField(max_length=20, unique=True)),
                ('tipo_entrada', models.CharField(max_length=20, unique=True)),
                ('cantidad', models.IntegerField(default=0)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_pagar', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('qr', models.ImageField(blank=True, null=True, upload_to='qr/')),
            ],
        ),
    ]
