# Generated by Django 5.2.6 on 2025-10-03 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_cliente', models.CharField(editable=False, max_length=100, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('celular', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=50)),
                ('tipo_entrada', models.CharField(choices=[('FULL ACCES', 'Full Acces'), ('EMPRESARIAL', 'Empresarial'), ('EMPRENDEDOR', 'Emprendedor')], default='FULL ACCES', max_length=20)),
                ('paquete', models.CharField(blank=True, max_length=100, null=True)),
                ('cantidad', models.IntegerField(default=0)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_pagar', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('qr', models.ImageField(blank=True, null=True, upload_to='qr/')),
                ('pago_confirmado', models.BooleanField(default=False)),
                ('usado', models.BooleanField(default=False)),
                ('entrada_usada', models.BooleanField(default=False)),
                ('token', models.CharField(blank=True, editable=False, max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('enviado', models.BooleanField(default=False)),
                ('mensaje', models.TextField(blank=True)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.participante')),
            ],
        ),
    ]
