# Generated by Django 5.2.6 on 2025-09-09 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='apellidos',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='participante',
            name='celular',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='participante',
            name='correo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='participante',
            name='dni',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='participante',
            name='tipo_entrada',
            field=models.CharField(max_length=20),
        ),
    ]
