# Generated by Django 5.2.7 on 2025-10-09 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='celular',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='participante',
            name='dni',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
