# Generated by Django 5.2.7 on 2025-10-10 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_alter_participante_celular_alter_participante_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='vendedor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
