# Generated by Django 5.2.6 on 2025-09-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_alter_participante_apellidos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='apellidos',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='participante',
            name='correo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='participante',
            name='dni',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='participante',
            name='tipo_entrada',
            field=models.CharField(choices=[('FULL ACCES', 'Full Acces'), ('EMPRESARIAL', 'Empresarial'), ('VIP', 'VIP'), ('GENERAL', 'General')], default='GENERAL', max_length=20),
        ),
    ]
