# Generated by Django 5.2.6 on 2025-09-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_alter_participante_apellidos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='cod_cliente',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='participante',
            name='tipo_entrada',
            field=models.CharField(choices=[('FULL ACCES', 'Full Acces'), ('EMPRESARIAL', 'Empresarial'), ('EMPRENDEDOR', 'Emprendedor')], default='FULL ACCES', max_length=20),
        ),
    ]
