# Generated by Django 5.2.6 on 2025-09-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_alter_participante_cod_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
    ]
