# Generated by Django 5.2.6 on 2025-09-10 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_participante_pagado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participante',
            old_name='pagado',
            new_name='pago_confirmado',
        ),
    ]
