# Generated by Django 5.2.7 on 2025-10-16 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_previaparticipantes_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='previaparticipantes',
            name='celular',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
