# Generated by Django 5.2.7 on 2025-10-16 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_previaparticipantes_celular'),
    ]

    operations = [
        migrations.AddField(
            model_name='previaparticipantes',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='qrs/'),
        ),
        migrations.DeleteModel(
            name='Voucher',
        ),
    ]
