# Generated by Django 5.2.6 on 2025-09-10 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_rename_pagado_participante_pago_confirmado'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('enviado', models.BooleanField(default=False)),
                ('mensaje', models.TextField(blank=True)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.participante')),
            ],
        ),
    ]
