# Generated by Django 5.2.6 on 2025-09-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_registrocorreo'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='usado',
            field=models.BooleanField(default=False),
        ),
    ]
