# Generated by Django 5.2.6 on 2025-09-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0008_participante_usado'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='entrada_usada',
            field=models.BooleanField(default=False),
        ),
    ]
