# Generated by Django 5.2.7 on 2025-10-17 17:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0009_alter_previaparticipantes_cod_part'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='validado_administracion',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='validado_contabilidad',
        ),
        migrations.AddField(
            model_name='previaparticipantes',
            name='fecha_validacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='previaparticipantes',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='previaparticipantes',
            name='validado_administracion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='previaparticipantes',
            name='validado_contabilidad',
            field=models.BooleanField(default=False),
        ),
    ]
