# Generated by Django 5.2.7 on 2025-10-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0010_remove_voucher_validado_administracion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='validado_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participante',
            name='validado_contabilidad',
            field=models.BooleanField(default=False),
        ),
    ]
