# Generated by Django 5.2.7 on 2025-10-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0011_participante_validado_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='precio_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
