# Generated by Django 5.2.7 on 2025-10-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0012_participante_precio_final'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participante',
            name='precio_final',
        ),
        migrations.AlterField(
            model_name='participante',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
