# Generated by Django 5.2.7 on 2025-10-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0013_remove_participante_precio_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='previaparticipantes',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='participante',
            name='correo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='participante',
            name='tipo_entrada',
            field=models.CharField(choices=[('FULL ACCES', 'Full Acces'), ('EMPRESARIAL', 'Empresarial'), ('EMPRENDEDOR', 'Emprendedor')], max_length=20),
        ),
    ]
