# Generated by Django 5.2.7 on 2025-10-29 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0014_previaparticipantes_correo_alter_participante_correo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='previaparticipante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vouchers_previa', to='cliente.previaparticipantes'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='participante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='cliente.participante'),
        ),
    ]
