# Generated by Django 5.2.7 on 2025-12-01 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0015_voucher_previaparticipante_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='previaparticipantes',
            name='asesor',
        ),
        migrations.RemoveField(
            model_name='previaparticipantes',
            name='validado_administracion',
        ),
        migrations.RemoveField(
            model_name='previaparticipantes',
            name='validado_contabilidad',
        ),
        migrations.AlterField(
            model_name='participante',
            name='tipo_entrada',
            field=models.CharField(choices=[('FULL ACCESS', 'Full Access'), ('EMPRESARIAL', 'Empresarial'), ('EMPRENDEDOR', 'Emprendedor')], max_length=20),
        ),
    ]
