# Generated by Django 5.2.7 on 2025-12-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0016_remove_previaparticipantes_asesor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='previaparticipantes',
            name='hora_ingreso',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='previaparticipantes',
            name='ingreso',
            field=models.BooleanField(default=False),
        ),
    ]
