# Generated by Django 5.2.7 on 2025-12-02 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0017_previaparticipantes_hora_ingreso_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='previaparticipantes',
            old_name='ingreso',
            new_name='entrada_usada',
        ),
    ]
