# Generated by Django 5.2.7 on 2025-12-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0018_rename_ingreso_previaparticipantes_entrada_usada'),
    ]

    operations = [
        migrations.AddField(
            model_name='previaparticipantes',
            name='enviado',
            field=models.BooleanField(default=False),
        ),
    ]
