# Generated by Django 5.2.7 on 2025-12-15 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0019_previaparticipantes_enviado'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailEnviado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario', models.EmailField(max_length=254)),
                ('asunto', models.CharField(max_length=255)),
                ('cuerpo_html', models.TextField()),
                ('enviado', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, null=True)),
                ('message_id', models.CharField(blank=True, help_text='Mesaage ID de SendGrid', max_length=255, null=True)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='cliente.previaparticipantes')),
            ],
        ),
    ]
