# Generated by Django 5.2.7 on 2025-12-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0020_emailenviado'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailenviado',
            name='adjunto',
            field=models.ImageField(blank=True, null=True, upload_to='email_adjuntos/'),
        ),
    ]
