# Generated by Django 6.0.5 on 2026-05-29 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0021_emailenviado_adjunto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Evento')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_evento', models.DateField(blank=True, null=True, verbose_name='Fecha del Evento')),
                ('smtp_host', models.CharField(default='smtp.sendgrid.net', max_length=255, verbose_name='Servidor SMTP')),
                ('smtp_port', models.IntegerField(default=587, verbose_name='Puerto SMTP')),
                ('smtp_use_tls', models.BooleanField(default=True, verbose_name='Usar TLS')),
                ('smtp_user', models.CharField(default='apikey', max_length=255, verbose_name='Usuario SMTP')),
                ('smtp_password', models.CharField(blank=True, max_length=255, null=True, verbose_name='Contraseña SMTP / API Key')),
                ('default_from_email', models.CharField(default='Soporte Círculo 50k <soporte.circulo50k@hilariogrp.com>', max_length=255, verbose_name='Remitente por Defecto')),
                ('twilio_account_sid', models.CharField(blank=True, max_length=255, null=True, verbose_name='Twilio Account SID')),
                ('twilio_auth_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Twilio Auth Token')),
                ('twilio_whatsapp_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número WhatsApp Twilio')),
                ('twilio_phone_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número Teléfono Twilio')),
                ('imgbb_api_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='ImgBB API Key')),
                ('color_primario', models.CharField(default='#7b1fa2', max_length=7, verbose_name='Color de Interfaz (HEX)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='event_logos/', verbose_name='Logo del Evento')),
                ('imagen_fondo', models.ImageField(blank=True, null=True, upload_to='event_backgrounds/', verbose_name='Fondo del Boleto (asesor.jpeg)')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='event_banners/', verbose_name='Banner de Cabecera')),
            ],
        ),
        migrations.AlterField(
            model_name='emailenviado',
            name='message_id',
            field=models.CharField(blank=True, help_text='Message ID de SendGrid', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='participante',
            name='correo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='participante',
            name='tipo_entrada',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='previaparticipantes',
            name='celular',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='previaparticipantes',
            name='cod_part',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='participante',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='cliente.evento'),
        ),
        migrations.AddField(
            model_name='previaparticipantes',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previa_participantes', to='cliente.evento'),
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('SUPERADMIN', 'Super Administrador (Toma todo)'), ('ORGANIZADOR', 'Organizador de Empresa (Gestión de Evento)'), ('REGISTRADOR', 'Registrador de Entradas / Validador (Puerta)')], default='REGISTRADOR', max_length=20, verbose_name='Rol de Usuario')),
                ('eventos', models.ManyToManyField(blank=True, related_name='usuarios_autorizados', to='cliente.evento', verbose_name='Eventos Asignados')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_entrada', models.CharField(max_length=100, verbose_name='Tipo de Entrada (VIP, General, etc.)')),
                ('preventa_1', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio Preventa 1')),
                ('preventa_2', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio Preventa 2')),
                ('preventa_3', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio Preventa 3')),
                ('puerta', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio Puerta')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='cliente.evento')),
            ],
        ),
        migrations.AddField(
            model_name='participante',
            name='tarifa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='participantes', to='cliente.tarifa'),
        ),
    ]
