# Generated by Django 6.0.5 on 2026-05-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0022_evento_alter_emailenviado_message_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='whatsapp_api_headers',
            field=models.TextField(blank=True, help_text='Ej:\nAuthorization: Bearer mi-token\nX-API-Key: mi-key', null=True, verbose_name='Cabeceras HTTP (Key: Value por línea)'),
        ),
        migrations.AddField(
            model_name='evento',
            name='whatsapp_api_payload',
            field=models.TextField(blank=True, help_text='Puedes usar variables como: {celular}, {nombres}, {evento}, {entradas}, {url_imagen}', null=True, verbose_name='Cuerpo JSON de la API (Payload)'),
        ),
        migrations.AddField(
            model_name='evento',
            name='whatsapp_api_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='URL de la API de WhatsApp'),
        ),
        migrations.AddField(
            model_name='evento',
            name='whatsapp_provider',
            field=models.CharField(choices=[('INACTIVE', 'Inactivo'), ('TWILIO', 'Twilio (Legacy)'), ('CUSTOM_API', 'Custom API Gateway (YCloud, Whapi, etc.)')], default='INACTIVE', max_length=20, verbose_name='Proveedor de WhatsApp'),
        ),
    ]
