# Generated by Django 6.0.5 on 2026-05-29 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0023_evento_whatsapp_api_headers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='aforo_maximo',
            field=models.IntegerField(default=500, verbose_name='Aforo Máximo'),
        ),
        migrations.AddField(
            model_name='evento',
            name='limite_entradas_persona',
            field=models.IntegerField(default=5, verbose_name='Límite de Entradas por Persona'),
        ),
    ]
