# Generated by Django 5.2.7 on 2026-10-08 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0032_enlazar_fondo_entrada_ede'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.CharField(max_length=500, unique=True)),
                ('contenido', models.BinaryField()),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
