# Generated by Django 5.2.7 on 2026-10-08 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0033_archivo_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifa',
            name='fecha_desde',
            field=models.DateField(blank=True, null=True, verbose_name='Válida desde (fecha)'),
        ),
        migrations.AddField(
            model_name='tarifa',
            name='fecha_hasta',
            field=models.DateField(blank=True, null=True, verbose_name='Válida hasta (fecha)'),
        ),
    ]
