# Generated by Django 5.2.7 on 2026-10-08 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0034_tarifa_vigencia_fechas'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='metodo_pago',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Método de pago'),
        ),
        migrations.AddField(
            model_name='participante',
            name='notas',
            field=models.TextField(blank=True, null=True, verbose_name='Notas / detalle de la venta'),
        ),
        migrations.AddField(
            model_name='participante',
            name='referencia_externa',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Referencia externa (fila de la hoja)'),
        ),
        migrations.AddField(
            model_name='participante',
            name='voucher_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Enlace al comprobante'),
        ),
    ]
