# Generated by Django 5.2.7 on 2026-10-08 01:58

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0035_participante_datos_hoja_ventas'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='autorizado_por',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Descuento / cortesía autorizado por'),
        ),
        migrations.AddField(
            model_name='participante',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Monto pagado acumulado'),
        ),
        migrations.CreateModel(
            name='PagoParticipante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('metodo_pago', models.CharField(blank=True, max_length=60, null=True)),
                ('voucher_url', models.URLField(blank=True, max_length=500, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('registrado_por', models.CharField(blank=True, max_length=255, null=True)),
                ('referencia_externa', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='cliente.participante')),
            ],
            options={
                'ordering': ['fecha', 'id'],
            },
        ),
    ]
