# Generated by Django 5.2.7 on 2026-10-09 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0037_participante_whatsapp_enviado'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoPuerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, verbose_name='Dispositivo / persona')),
                ('codigo_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('vence_en', models.DateTimeField(verbose_name='Vence')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('ultimo_uso', models.DateTimeField(blank=True, null=True)),
                ('escaneos', models.PositiveIntegerField(default=0)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_puerta', to='cliente.evento')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
    ]
