# Generated by Django 5.2.7 on 2026-03-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='nombre',
        ),
        migrations.AddField(
            model_name='lote',
            name='height',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lote',
            name='width',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lote',
            name='x',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lote',
            name='y',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
