# Generated by Django 5.2.7 on 2026-03-16 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0002_remove_lote_nombre_lote_height_lote_width_lote_x_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plano',
            name='archivo_pdf',
        ),
        migrations.AddField(
            model_name='plano',
            name='imagen',
            field=models.ImageField(default='planos/default.png', upload_to='planos/'),
            preserve_default=False,
        ),
    ]
