# Generated by Django 5.2.7 on 2026-03-20 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0003_remove_plano_archivo_pdf_plano_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='puntos',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='width',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
