# Generated by Django 5.2.7 on 2026-06-05 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0008_lote_precio_lote_separado_en_lote_vendido_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd_pen', models.DecimalField(decimal_places=4, default=3.75, max_digits=8)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
