# Generated by Django 5.2.7 on 2026-06-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0009_tipocambio'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
